import { createSlice } from "@reduxjs/toolkit"

const initialState={
    numOfCakes: 10
}
// createSlice will automatically create action creators with the same name as the reducers function we
// have given that is ordered and restocked and apart from action creators it also returns main reducer
// function which we can provide to our redux store

// action type/constants will be the suffixName/reducer name, that is cake/ordered and cake/restocked
// action creator will be ordered and restocked

// the reducer of a slice will only respond to the actions type generated by the slice
// if we want the reducer of a slice will respond to the actions of other slice we need to define extrareducers
// to define extrareducers there are two types
// first is mapping method where the key is action type of other slice and value as reducer function
// second is using builder function
const cakeSlice=createSlice({
    name: 'cake',
    initialState: initialState,
    reducers: {
        ordered: (state)=>{//here we can directly mutate the state and behind the scenes it uses the immer library
            state.numOfCakes--;
        },
        restocked: (state, action)=>{
            state.numOfCakes+=action.payload;
        },
    },
})
export const cakeActions = cakeSlice.actions; // export actions as named exports
export default cakeSlice.reducer; // export reducer as default export