import { createSlice } from "@reduxjs/toolkit"
// this is the way to write code in redux toolkit, add adding suffix Slice is a convention/must
const initialState={
    numOfCakes: 10
}
// createSlice will automatically create action creators with the same name as the reducers function we
// have given that is ordered and restocked and apart from action creators it also returns main reducer
// function which we can provide to our redux store

// action type will be the suffixName(of the const that is cake)/reducer name
// here action type will be cake/ordered and cake/restocked

// the reducer of a slice will only respond to the actions type generated by the slice
// if we want the reducer of a slice will respond to the actions of other slice we need to define extrareducers
// to define extrareducers there are two types
// first is mapping method where the key is action type of other slice and value as reducer function
// second is using builder function
const cakeSlice=createSlice({
    name: 'cake',
    initialState: initialState,
    reducers: {
        ordered: (state)=>{//here we can directly mutate the state and behind the scenes it uses the immer library
            state.numOfCakes--;
        },
        restocked: (state, action)=>{
            state.numOfCakes+=action.payload;
        },
    },
})
export const cakeActions = cakeSlice.actions; // export actions as named exports
export default cakeSlice.reducer; // export reducer as default export